### ISSUE TITLE
OpenSSL found error

### ISSUE THREAD

**Issue by chessnokov** [flathub/dev.zed.Zed#21]
After start Zed printed in terminal:

```
flatpak: /var/lib/flatpak/app/dev.zed.Zed/x86_64/stable/43109795a0a1489151b14d6bc71ebb7b3117a420fd59353f339ac8a28f1fdc75/files/lib/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /lib64/libcurl.so.4)
```

**Comment by tomaswarynyca** [comment]
Is this problem fixed in the latest version?

In my case I don't have the error anymore

**Comment by tomaswarynyca** [comment]
@jerome-benoit @chessnokov could you check your console to see if the problem persists?

**Comment by jerome-benoit** [comment]
No, the issue has been fixed upstream since 0.155.x.

**Comment by teohhanhui** [comment]
This does not seem to be fixed yet in the latest Zed 0.156.1

> flatpak: /var/lib/flatpak/app/dev.zed.Zed/aarch64/stable/7c8225331b5806d594e474323074642ed1f6e9b71779fa547afcd7cd40df1b8d/files/lib/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /lib64/libcurl.so.4)

I've tried deleting `~/.var/dev.zed.Zed` and starting from scratch, but the problem persists.
